databases:
  - name: mydb
    plan: free

services:
  - type: web
    name: openmrs-server
    env: docker
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: OPENMRS_DB_HOST
        value: mydb
      - key: OPENMRS_DB_PORT
        value: "5432"
      - key: OPENMRS_DB_USER
        value: openmrsuser
      - key: OPENMRS_DB_PASSWORD
        value: ""
      - key: OPENMRS_DB_NAME
        value: openmrsdb
