databases:
  - name: mydb
    databaseName: openmrsdb
    user: openmrsuser
    plan: free

services:
  - type: web
    name: openmrs-server
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENMRS_DB_HOST
        value: mydb
      - key: OPENMRS_DB_PORT
        value: "5432"
      - key: OPENMRS_DB_USER
        value: openmrsuser
      - key: OPENMRS_DB_PASSWORD
        fromDatabase: mydb:password
      - key: OPENMRS_DB_NAME
        value: openmrsdb
